// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnUYe5wPug6wH1iii4nwIdkmvkJLO1z-c',
    appId: '1:338386092823:web:89d529389f4dbd2a41ad52',
    messagingSenderId: '338386092823',
    projectId: 'project2-cefa4',
    authDomain: 'project2-cefa4.firebaseapp.com',
    storageBucket: 'project2-cefa4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3102WvE_SSYikT-QppvG25ov1C-jjXpA',
    appId: '1:338386092823:android:310d468a728ec58741ad52',
    messagingSenderId: '338386092823',
    projectId: 'project2-cefa4',
    storageBucket: 'project2-cefa4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF5CqVKOK3qrNu2m1QFI1zLIx1uSVvPKk',
    appId: '1:338386092823:ios:fb0d1ecf651927c241ad52',
    messagingSenderId: '338386092823',
    projectId: 'project2-cefa4',
    storageBucket: 'project2-cefa4.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF5CqVKOK3qrNu2m1QFI1zLIx1uSVvPKk',
    appId: '1:338386092823:ios:fb0d1ecf651927c241ad52',
    messagingSenderId: '338386092823',
    projectId: 'project2-cefa4',
    storageBucket: 'project2-cefa4.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnUYe5wPug6wH1iii4nwIdkmvkJLO1z-c',
    appId: '1:338386092823:web:7f3e5e78bf62708f41ad52',
    messagingSenderId: '338386092823',
    projectId: 'project2-cefa4',
    authDomain: 'project2-cefa4.firebaseapp.com',
    storageBucket: 'project2-cefa4.firebasestorage.app',
  );
}
